/*
 * This header is generated by sopc2dts on Fri Feb 15 19:27:38 EST 2013
 * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>
 * in cooperation with the nios2 community <Nios2-dev@sopc.et.ntust.edu.tw>
 */
#ifndef CUSTOM_FPGA_H_
#define CUSTOM_FPGA_H_

/* generated from synapse.sopcinfo */

/* Dumping slaves of nios2_qsys_0.data_master*/

/* nios2_qsys_0.jtag_debug_module is a altera_nios2_qsys */
#define CONFIG_SYS_CLK_FREQ	100000000
#define CONFIG_SYS_DCACHE_SIZE	2048
#define CONFIG_SYS_DCACHELINE_SIZE	32
#define CONFIG_SYS_ICACHELINE_SIZE	32
#define CONFIG_SYS_EXCEPTION_ADDR	0xc0000020
#define CONFIG_SYS_ICACHE_SIZE	4096
#define CONFIG_SYS_RESET_ADDR	0xc9f20000
#define IO_REGION_BASE	0xE0000000

/* altpll_0.pll_slave is a altpll */
#define ALTPLL_0_BASE	0xe4000800

/* ddr3_1.avl is a altera_mem_if_ddr3_emif */
#define CONFIG_SYS_SDRAM_BASE	0xc0000000
#define CONFIG_SYS_SDRAM_SIZE	0x4000000

/* cfi_flash.uas is a altera_generic_tristate_controller */
#define CONFIG_SYS_FLASH_BASE	0xe8000000
#define CONFIG_FLASH_CFI_DRIVER
#define CONFIG_SYS_CFI_FLASH_STATUS_POLL /* fix amd flash issue */
#define CONFIG_SYS_FLASH_CFI
#define CONFIG_SYS_FLASH_USE_BUFFER_WRITE
#define CONFIG_SYS_FLASH_PROTECTION
#define CONFIG_SYS_MAX_FLASH_BANKS 1
#define CONFIG_SYS_MAX_FLASH_SECT 1024

/* mm_clock_crossing_bridge_0.s0 is a altera_avalon_mm_clock_crossing_bridge */
/* Dumping slaves of mm_clock_crossing_bridge_0.m0*/

/* uart_0.s1 is a altera_avalon_uart */
#define CONFIG_SYS_UART_BAUD	115200
#define CONFIG_SYS_UART_BASE	0xe7000180
#define CONFIG_SYS_UART_FREQ	50000000

/* timer.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_IRQ	0
#define CONFIG_SYS_TIMER_FREQ	50000000
#define CONFIG_SYS_TIMER_BASE	0xe7000080

/* led_reg.s1 is a altera_avalon_pio */
#define LED_REG_BASE	0xe7000100

/* sysid_qsys_0.control_slave is a altera_avalon_sysid_qsys */
#define CONFIG_SYS_SYSID_BASE	0xe7000000

/* labx_video_depacketizer_0.Host_Interface is a labx_video_depacketizer */
#define LABX_VIDEO_DEPACKETIZER_0_BASE	0xe7010000
#define LABX_VIDEO_DEPACKETIZER_0_IRQ	6

/* labx_presentation_dma.Host_Interface is a labx_dma_coprocessor */
#define LABX_PRESENTATION_DMA_BASE	0xe7008000
#define LABX_PRESENTATION_DMA_IRQ	7

/* labx_serializer_dma.Host_Interface is a labx_dma_coprocessor */
#define LABX_SERIALIZER_DMA_BASE	0xe700a000
#define LABX_SERIALIZER_DMA_IRQ	8

/* labx_video_clock_recovery_0.Host_Interface is a labx_video_clock_recovery */
#define LABX_VIDEO_CLOCK_RECOVERY_0_BASE	0xe700c000
#define LABX_VIDEO_CLOCK_RECOVERY_0_IRQ	9

/* labx_ethernet_1.Host_Interface is a labx_ethernet */
#define LABX_ETHERNET_1_BASE	0xe7040000
#define LABX_ETHERNET_1_IRQ	11

/* labx_ptp_0.host_interface is a labx_ptp */
#define LABX_PTP_0_BASE	0xe4110000
#define LABX_PTP_0_IRQ	2

/* labx_ethernet_0.Host_Interface is a labx_ethernet */
#define LABX_ETHERNET_0_BASE	0xe4100000
#define LABX_ETHERNET_0_IRQ	3

/* video_input_0.avalon_slave_0 is a Video_Input */
#define VIDEO_INPUT_0_BASE	0xe4120000
#define VIDEO_INPUT_0_IRQ	4

/* labx_multi_packetizer_0.host_interface is a labx_multi_packetizer */
#define LABX_MULTI_PACKETIZER_0_BASE	0xe4130000
#define LABX_MULTI_PACKETIZER_0_IRQ	5

/* labx_shaping_dma_0.host_interface is a labx_shaping_dma */
#define LABX_SHAPING_DMA_0_BASE	0xe4140000

/* video_input_1.avalon_slave_0 is a Video_Input */
#define VIDEO_INPUT_1_BASE	0xe4124000
#define VIDEO_INPUT_1_IRQ	10

#endif	//CUSTOM_FPGA_H_
