/*
 * (C) Copyright 2010, Thomas Chou <thomas@wytron.com.tw>
 *
 * Licensed under the GPL-2 or later.
 *
 * This file is generated by sopc-create-config-files.
 */
#ifndef _NEEK_OCM_SPI_MMU_H_
#define _NEEK_OCM_SPI_MMU_H_

/* generated from cycloneIII_embedded_evaluation_kit_standard_sopc.sopc */

/* cpu.data_master is a altera_nios2 */
#define CONFIG_SYS_CLK_FREQ 100000000
#define CONFIG_SYS_RESET_ADDR 0xc4000000
#define CONFIG_SYS_EXCEPTION_ADDR 0xc0000020
#define CONFIG_SYS_ICACHE_SIZE 8192
#define CONFIG_SYS_ICACHELINE_SIZE 32
#define CONFIG_SYS_DCACHE_SIZE 4096
#define CONFIG_SYS_DCACHELINE_SIZE 32
#define IO_REGION_BASE 0xe0000000

/* mmc_spi.spi_control_port is a altera_avalon_spi */
#define MMC_SPI_BASE 0xe8001300
#define CONFIG_SYS_ALTERA_SPI_LIST { MMC_SPI_BASE }
#define CONFIG_ALTERA_SPI
#define CONFIG_CMD_SPI
#define CONFIG_CMD_MMC
#define CONFIG_MMC
#define CONFIG_GENERIC_MMC
#define CONFIG_CMD_MMC_SPI
#define CONFIG_MMC_SPI
#define CONFIG_MMC_SPI_BUS 0
#define CONFIG_MMC_SPI_CS 0
#define CONFIG_MMC_SPI_SPEED 30000000
#define CONFIG_MMC_SPI_MODE SPI_MODE_3
#define CONFIG_CMD_FAT
#define CONFIG_DOS_PARTITION

/* ssram.s1 is a altera_avalon_cy7c1380_ssram */
#define CONFIG_SYS_SRAM_BASE 0xc5000000
#define CONFIG_SYS_SRAM_SIZE 0x00100000

/* sysid.control_slave is a altera_avalon_sysid */
#define CONFIG_SYS_SYSID_BASE 0xe8001400

/* jtag_uart.avalon_jtag_slave is a altera_avalon_jtag_uart */
#define CONFIG_SYS_JTAG_UART_BASE 0xe8001410

/* uart.s1 is a altera_avalon_uart */
#define CONFIG_SYS_UART_BASE 0xe8001340
#define CONFIG_SYS_UART_FREQ 66500000
#define CONFIG_SYS_UART_BAUD 115200

/* gpio_0.avalon_slave_0 is a gpio */
#define CONFIG_SYS_GPIO_BASE 0xe8001500

/* Added manually by emount! */
#define CONFIG_SYS_GPIO_WIDTH 4

/* sys_clk_timer.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_BASE 0xe8001240
#define CONFIG_SYS_TIMER_IRQ 0
#define CONFIG_SYS_TIMER_FREQ 60000000

/* ddr_sdram.s1 is a altmemddr */
#define CONFIG_SYS_SDRAM_BASE 0xc0000000
#define CONFIG_SYS_SDRAM_SIZE 0x02000000

/* ext_flash.s1 is a altera_avalon_cfi_flash */
#define CONFIG_SYS_FLASH_BASE 0xe4000000
#define CONFIG_FLASH_CFI_DRIVER
#define CONFIG_SYS_CFI_FLASH_STATUS_POLL /* fix amd flash issue */
#define CONFIG_SYS_FLASH_CFI
#define CONFIG_SYS_FLASH_USE_BUFFER_WRITE
#define CONFIG_SYS_FLASH_PROTECTION
#define CONFIG_SYS_MAX_FLASH_BANKS 1
#define CONFIG_SYS_MAX_FLASH_SECT 1024

/* igor_mac.control_port is a eth_ocm */
#define CONFIG_SYS_ETHOC_BASE 0xe8000000
#define CONFIG_ETHOC

#endif /* _NEEK_OCM_SPI_MMU_H_ */
