/*
 * This header is generated by sopc2dts on Tue Apr 09 21:41:57 EDT 2013
 * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>
 * in cooperation with the nios2 community <Nios2-dev@sopc.et.ntust.edu.tw>
 */
#ifndef CUSTOM_FPGA_H_
#define CUSTOM_FPGA_H_

/* generated from avb_video_s4gx.sopcinfo */

/* Dumping slaves of nios2_qsys_0.data_master*/

/* nios2_qsys_0.jtag_debug_module is a altera_nios2_qsys */
#define CONFIG_SYS_CLK_FREQ	100000000
#define CONFIG_SYS_DCACHE_SIZE	2048
#define CONFIG_SYS_DCACHELINE_SIZE	32
#define CONFIG_SYS_ICACHELINE_SIZE	32
#define CONFIG_SYS_EXCEPTION_ADDR	0xc0000020
#define CONFIG_SYS_ICACHE_SIZE	4096
#define CONFIG_SYS_RESET_ADDR	0xccc20000
#define IO_REGION_BASE	0xE0000000

/* altpll_0.pll_slave is a altpll */
#define ALTPLL_0_BASE	0xe82224c0

/* ddr3_bot.avl is a altera_mem_if_ddr3_emif */
#define CONFIG_SYS_SDRAM_BASE	0xc0000000
#define CONFIG_SYS_SDRAM_SIZE	0x8000000

/* cfi_flash.uas is a altera_generic_tristate_controller */
#define CONFIG_SYS_FLASH_BASE	0xec000000
#define CONFIG_FLASH_CFI_DRIVER
#define CONFIG_SYS_CFI_FLASH_STATUS_POLL /* fix amd flash issue */
#define CONFIG_SYS_FLASH_CFI
#define CONFIG_SYS_FLASH_USE_BUFFER_WRITE
#define CONFIG_SYS_FLASH_PROTECTION
#define CONFIG_SYS_MAX_FLASH_BANKS 1
#define CONFIG_SYS_MAX_FLASH_SECT 1024

/* mm_clock_crossing_bridge_0.s0 is a altera_avalon_mm_clock_crossing_bridge */
/* Dumping slaves of mm_clock_crossing_bridge_0.m0*/

/* uart_0.s1 is a altera_avalon_uart */
#define CONFIG_SYS_UART_BAUD	115200
#define CONFIG_SYS_UART_BASE	0xeb000180
#define CONFIG_SYS_UART_FREQ	50000000

/* timer.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_IRQ	0
#define CONFIG_SYS_TIMER_FREQ	50000000
#define CONFIG_SYS_TIMER_BASE	0xeb000080

/* led_reg.s1 is a altera_avalon_pio */
#define LED_REG_BASE	0xeb000100

/* sysid_qsys_0.control_slave is a altera_avalon_sysid_qsys */
#define CONFIG_SYS_SYSID_BASE	0xeb000000

/* labx_ptp_0.Host_Interface is a labx_ptp */
#define LABX_PTP_0_BASE	0xe8310000
#define LABX_PTP_0_IRQ	2

/* labx_ethernet_0.Host_Interface is a labx_ethernet */
#define LABX_ETHERNET_0_BASE	0xe8300000
#define LABX_ETHERNET_0_IRQ	3

#endif	//CUSTOM_FPGA_H_
