/*
 * This header is generated by sopc2dts
 * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>
 * in cooperation with the nios2 community <Nios2-dev@sopc.et.ntust.edu.tw>
 */
#ifndef CUSTOM_FPGA_H_
#define CUSTOM_FPGA_H_

/* generated from DE2_115_SOPC.sopcinfo */

/* Dumping slaves of cpu.data_master*/

/* cpu.jtag_debug_module is a altera_nios2 */
#define CONFIG_SYS_CLK_FREQ	100000000
#define CONFIG_SYS_DCACHE_SIZE	2048
#define CONFIG_SYS_DCACHELINE_SIZE	32
#define CONFIG_SYS_ICACHELINE_SIZE	32
#define CONFIG_SYS_EXCEPTION_ADDR	0xc0000020
#define CONFIG_SYS_ICACHE_SIZE	4096
#define CONFIG_SYS_RESET_ADDR	0xc9810000
#define IO_REGION_BASE	0xE0000000

/* clock_crossing_io.s1 is a altera_avalon_clock_crossing */
/* Dumping slaves of clock_crossing_io.m1*/

/* timer.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_IRQ	1
#define CONFIG_SYS_TIMER_FREQ	10000000
#define CONFIG_SYS_TIMER_BASE	0xEB000000

/* sysid.control_slave is a altera_avalon_sysid */
#define CONFIG_SYS_SYSID_BASE	0xEB000140

/* key.s1 is a altera_avalon_pio */
#define KEY_BASE	0xEB000060
#define KEY_IRQ	2

/* sw.s1 is a altera_avalon_pio */
#define SW_BASE	0xEB000070
#define SW_IRQ	3

/* ledg.s1 is a altera_avalon_pio */
#define LEDG_BASE	0xEB000080

/* ledr.s1 is a altera_avalon_pio */
#define LEDR_BASE	0xEB000090

/* rs232.s1 is a altera_avalon_uart */
#define CONFIG_SYS_UART_BAUD	115200
#define CONFIG_SYS_UART_BASE	0xEB000020
#define CONFIG_SYS_UART_FREQ	10000000

/* i2c_scl.s1 is a altera_avalon_pio */
#define I2C_SCL_BASE	0xEB0000A0

/* i2c_sda.s1 is a altera_avalon_pio */
#define I2C_SDA_BASE	0xEB0000B0

/* eep_i2c_scl.s1 is a altera_avalon_pio */
#define EEP_I2C_SCL_BASE	0xEB0000C0

/* eep_i2c_sda.s1 is a altera_avalon_pio */
#define EEP_I2C_SDA_BASE	0xEB0000D0

/* ir.s1 is a altera_avalon_pio */
#define IR_BASE	0xEB0000F0

/* usb_mailbox_0.slave_interface is a usb_mailbox */
#define USB_MAILBOX_0_BASE	0xEB004000
#define USB_MAILBOX_0_IRQ	5

/* sdram.s1 is a altera_avalon_new_sdram_controller */
#define CONFIG_SYS_SDRAM_BASE	0xC0000000
#define CONFIG_SYS_SDRAM_SIZE	0x08000000

/* jtag_uart.avalon_jtag_slave is a altera_avalon_jtag_uart */
#define CONFIG_SYS_JTAG_UART_BASE	0xE82224D0

/* pll.pll_slave is a altpll */
#define PLL_BASE	0xE82224C0

/* cfi_flash.s1 is a altera_avalon_cfi_flash */
#define CONFIG_SYS_FLASH_BASE	0xE9800000
#define CONFIG_FLASH_CFI_DRIVER
#define CONFIG_SYS_CFI_FLASH_STATUS_POLL /* fix amd flash issue */
#define CONFIG_SYS_FLASH_CFI
#define CONFIG_SYS_FLASH_USE_BUFFER_WRITE
#define CONFIG_SYS_FLASH_PROTECTION
#define CONFIG_SYS_MAX_FLASH_BANKS 1
#define CONFIG_SYS_MAX_FLASH_SECT 1024

#endif	//CUSTOM_FPGA_H_
