/*
 * This header is generated by sopc2dts
 * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>
 * in cooperation with the nios2 community <Nios2-dev@sopc.et.ntust.edu.tw>
 */
#ifndef CUSTOM_FPGA_H_
#define CUSTOM_FPGA_H_

/* generated from eecpb_sopc.sopcinfo */

/* Dumping slaves of cpu.data_master*/

/* cpu.jtag_debug_module is a altera_nios2 */
#define CONFIG_SYS_CLK_FREQ	100000000
#define CONFIG_SYS_DCACHE_SIZE	2048
#define CONFIG_SYS_DCACHELINE_SIZE	32
#define CONFIG_SYS_ICACHELINE_SIZE	32
#define CONFIG_SYS_EXCEPTION_ADDR	0xc0000020
#define CONFIG_SYS_ICACHE_SIZE	4096
#define CONFIG_SYS_RESET_ADDR	0xca2a0000
#define IO_REGION_BASE	0xE0000000

/* altpll_0.pll_slave is a altpll */
#define ALTPLL_0_BASE	0xE82224C0

/* jtag_uart_0.avalon_jtag_slave is a altera_avalon_jtag_uart */
#define CONFIG_SYS_JTAG_UART_BASE	0xE82224D0

/* sdram.s1 is a altera_avalon_new_sdram_controller */
#define CONFIG_SYS_SDRAM_BASE	0xC0000000
#define CONFIG_SYS_SDRAM_SIZE	0x01000000

/* clock_crossing_io.s1 is a altera_avalon_clock_crossing */
/* Dumping slaves of clock_crossing_io.m1*/

/* timer.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_IRQ	1
#define CONFIG_SYS_TIMER_FREQ	10000000
#define CONFIG_SYS_TIMER_BASE	0xEB000020

/* sysid.control_slave is a altera_avalon_sysid */
#define CONFIG_SYS_SYSID_BASE	0xEB000000

/* IR_Decode_0.slave_interface is a IR_Decode */
#define IR_DECODE_0_BASE	0xEB000400
#define IR_DECODE_0_IRQ	5

/* usb_mailbox_0.slave_interface is a usb_mailbox */
#define USB_MAILBOX_0_BASE	0xEB002000
#define USB_MAILBOX_0_IRQ	6

/* ctl0_reg.s1 is a altera_avalon_pio */
#define CTL0_REG_BASE	0xEB000040

/* ctl1_reg.s1 is a altera_avalon_pio */
#define CTL1_REG_BASE	0xEB000060

/* osd0_reg.s1 is a altera_avalon_pio */
#define OSD0_REG_BASE	0xEB000080

/* osd1_reg.s1 is a altera_avalon_pio */
#define OSD1_REG_BASE	0xEB0000A0

/* stat0_reg.s1 is a altera_avalon_pio */
#define STAT0_REG_BASE	0xEB000010

/* uart_0.s1 is a altera_avalon_uart */
#define CONFIG_SYS_UART_BAUD	115200
#define CONFIG_SYS_UART_BASE	0xEB000180
#define CONFIG_SYS_UART_FREQ	10000000

/* remote_update_cycloneiii_0.s1 is a altera_avalon_remote_update_cycloneiii */
#define REMOTE_UPDATE_CYCLONEIII_0_BASE	0xEB000200

/* interrupt_reg.s1 is a altera_avalon_pio */
#define INTERRUPT_REG_BASE	0xEB0001A0
#define INTERRUPT_REG_IRQ	3

/* revision_reg.s1 is a altera_avalon_pio */
#define REVISION_REG_BASE	0xEB0001C0

/* hdmi_tx_i2c.s1 is a opencores_i2c_master */
#define HDMI_TX_I2C_BASE	0xEB000800
#define HDMI_TX_I2C_IRQ	4

/* hdmi_rx_i2c.s1 is a opencores_i2c_master */
#define HDMI_RX_I2C_BASE	0xEB000900
#define HDMI_RX_I2C_IRQ	7

/* temp_i2c.s1 is a opencores_i2c_master */
#define TEMP_I2C_BASE	0xEB000A00
#define TEMP_I2C_IRQ	8

/* video_top_0.slave_interface is a video_top */
#define VIDEO_TOP_0_BASE	0xEB020000

/* cfi_flash.s1 is a altera_avalon_cfi_flash */
#define CONFIG_SYS_FLASH_BASE	0xEA000000
#define CONFIG_FLASH_CFI_DRIVER
#define CONFIG_SYS_CFI_FLASH_STATUS_POLL /* fix amd flash issue */
#define CONFIG_SYS_FLASH_CFI
#define CONFIG_SYS_FLASH_USE_BUFFER_WRITE
#define CONFIG_SYS_FLASH_PROTECTION
#define CONFIG_SYS_MAX_FLASH_BANKS 1
#define CONFIG_SYS_MAX_FLASH_SECT 1024

#endif	//CUSTOM_FPGA_H_
